/*************************************************************
@Name: APTS_OrderConstantsTest 
@Author: Rajesh Patel
@CreateDate: 23-10-2018
@Description: Test Class APTS_OrderConstants 
@UsedBy: APTS_OrderConstants
******************************************************************/

//v100 23-10-2018 Rajesh Patel: Initial version.
//Comments in this format are mandatory for each change of code.
//Adding code comment example: v100++<< means start of changes and v100++>> means end of changes
//Removing code comment example: v100--<< means start of changes and v100-->> means end of changes


@isTest
private with sharing class APTS_OrderConstantsTest {

    @isTest
    static void testOrderConstants(){
        APTS_OrderConstants orderConsClass = new APTS_OrderConstants();
     }
}