//-------------------------------------------------------------------------------------------//
// Author       :   Rey Austral - Accenture
// Created Date :   May 11, 2017
// Usage        :   Static vale that is being used by the integration methods
//-------------------------------------------------------------------------------------------//
@isTest
public class INT_Constants {
    
    public static final string ACCOUNT = 'Account';
    public static final string ACCOUNT_LOCATION = 'Account Location';
    public static final string ASSET = 'Asset';
    public static final string INVOICE = 'Invoice';
    public static final string ORDER = 'Apttus_Config2__Order__c';
    public static final string WAITING_ON_PARENT_INTEGRATION = 'Waiting on Parent Integration';
    public static final string INITIAL = 'Initial';
    public static final string PAUSED = 'Paused';
    public static final string TARGET_SYSTEM_SUCCESS = 'Target System Success';
    public static final string TARGET_SYSTEM_ERROR = 'Target System Error';
    public static final string WOLI_CATS = 'Work Order Line Item - CATS-record';
    public static final string WOLI_CREATION_IO = 'Work Order Line Item - Creation I/O';
    public static final string WOLI_GOODS_MVMT = 'Work Order Line Item - Goods Mvmt';
    public static final string WOLI_ATTACHMENT = 'Work Order Line Item - Attachment';
    public static final string WOLI_CARSTOCK = 'Work Order Line Item - Car Stock Replenishment';
    public static final string WOLI_MISSINGPARTS = 'Work Order Line Item - Missing Parts Sales Order';
    public static final string WOLI_CREATEUPDATETASK = 'Click - TaskCreateOrUpdate';
    public static final string WOLI_CREATEUPDATE_OPERATING_TASK = 'Click - OperatingTask';
    public static final string WOLI_CREATEUPDATE_OPERATING_TASK_ROUTEITEM = 'Click - RouteOperatingTask_Item';
    public static final string WOLI_CREATEUPDATE_OPERATINGROUTE_TASK = 'Click - RouteOperatingTask';
    public static final string WOLI_CREATEUPDATE_COUNTERREADING_TASK = 'Click - CounterReadingTask';
    public static final string WOLI_CREATEUPDATE_ROUTESALES_TASK = 'Click - RouteSalesTask';
    public static final string CLICK_SESSIONID = 'Click - SessionId'; 
    
    public static final String CLICK_ATTACHMENT = 'Click - ATTACHMENT'; 
    public static final String CLICK_NOTIFICATION = 'Click - ClickNotification'; 
    public static final String CLICK_GETAVAILABLESLOTS = 'Click - GetAvailableSlot'; 
    public static final String CLICK_GETAVAILABLESLOTS_PERFORMANCE = 'Click - Performance GetAvailableSlot'; 
    public static final String CLICK_ATTACHMENTFILE = 'Attachment';
    public static final String CLICK_ATTACHMENT1FILE = 'Attachment1';
    public static final String CLICK_ATTACHMENT2FILE = 'Attachment2';
    public static final String CLICK_SIGNATUREFILE = 'Signature';
    public static final String CLICK_QUOTESIGNATUREFILE = 'Quote Signature';
    public static final string CLICK_SYNCMASTERPRODUCT = 'Click - Sync Master Product'; 
}